### ISSUE TITLE
setPanorama Bug

### ISSUE THREAD

**Issue by duoduodady** [mistic100/Photo-Sphere-Viewer#648] opened 2022-03-08 13:21 UTC
setPanorama method in the example file( equirectangular.html ) .
If you click the Change image button  '🔄' twice or more than twice, you will notice that the new pano will flash.

**Comment by duoduodady** [comment] 2022-03-08 13:40
The flash is very fast

https://user-images.githubusercontent.com/13536089/157247821-faeb9623-5dfe-4be8-847f-f916bb717948.mp4

**Comment by mistic100** [comment] 2022-03-08 17:05
I cannot reproduce on Firefox nor Chrome.

Something similiar happened on an old version but was fixed in version 4.5.3 https://github.com/mistic100/Photo-Sphere-Viewer/commit/9d777116091cb28ea91ae787710aec76605a89c0#diff-e3c70d261872a380c462c2f2245f20bfce644ae5ef852d07d0a626431e6a6ef0

**Comment by duoduodady** [comment] 2022-03-11 14:46
Thanks!

Yes, it was fixed in version 4.5.3

**Closed** 2022-03-11 14:49 UTC
