### ISSUE TITLE
PSV error when using plugins that were built from sources

### ISSUE THREAD

**Issue by EVOsparkLP** [mistic100/Photo-Sphere-Viewer#1497] opened 2024-11-25 15:40 UTC
### Describe the bug

When I install the Photo-Sphere-Viewer and some plugins with npm everything works fine.

But as I need to modify an existing plugin (gyroscope) I try to build the plugin from sources. When this "self-built" plugin is added to the viewer, I receive the following error:
`config.ts:216 Uncaught (in promise) PSVError: An undefined value was given for plugin 0.`

There are no code modifications in the plugin. I'm just trying to get the build process running.

What I did so far:
- cloned the Photo-Sphere-Viewer repository
- `npm install`
- `npm run build` (builds without errors; build is available in dist folder)

- included this build in my project:
```
import { Viewer } from '../../Photo-Sphere-Viewer-main/packages/core/dist';
import '../../Photo-Sphere-Viewer-main/packages/core/dist/index.css';
import { GyroscopePlugin } from '../../Photo-Sphere-Viewer-main/packages/gyroscope-plugin/dist';

...

this.viewer = new Viewer({
    container: document.querySelector('#psvContainer'),
    panorama: url,
    plugins: [
        [GyroscopePlugin, {
            moveMode: "smooth",
            absolutePosition: true,
            touchmove: false
        }]
    ],
});
```
- `npm run build` (builds without errors)

I tested the integration also with other plugins which did not work either. So I guess the issue is not specific for the gyroscope plugin.

Maybe this is no real bug, but I am just importing the build files in a wrong way? Can someone who has ever modiefied a plugin, share the steps to get this running? Thanks.

### Photo Sphere Viewer version

5.11.1

### Plugins loaded

Gyroscope

### OS & browser

Windows, Chrome

**Comment by mistic100** [comment] 2024-11-25 16:28
Did you put break points to check what is the actual value of `GyroscopePlugin` ?

Also try `import * as GyroscopePlugin` to check the whole JS module.

**Comment by mistic100** [comment] 2024-11-25 20:44
for sure your locally built "Photo-Sphere-Viewer-main/packages/gyroscope-plugin/dist" has somewhere an import from "@photo-sphere-viewer/core" which resolves successfully if you also have the package available.

The problem is that this check will never work because you actually have two different `AbstractPlugin`
https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/packages/core/src/plugins/AbstractPlugin.ts#L119

The solution : use the imports map as described in your setup https://photo-sphere-viewer.js.org/guide/#your-first-viewer  
And always use package name when importing stuff, only the imports map will reference the local files.  
This way you will have only one core module.

**Comment by mistic100** [comment] 2024-11-25 20:44
```html
<script type="importmap">
    {
        "imports": {
            "three": "https://cdn.jsdelivr.net/npm/three/build/three.module.js",
            "@photo-sphere-viewer/core": "../../Photo-Sphere-Viewer-main/packages/gyroscope-plugin/dist/index.module.js"
        }
    }
</script>
```

**Comment by mistic100** [comment] 2024-11-25 20:48
Closing as not an issue with the lib.

**Closed by mistic100** 2024-11-25 20:48 UTC
Labels: bug

**Comment by EVOsparkLP** [comment] 2024-11-25 21:29
Thanks for your fast support! I got it running.
As I am using vue.js I could not use the suggested way with the importmap.

Therefore I changed the package.json like this:
```
"@photo-sphere-viewer/core": "^5.11.1",
"@photo-sphere-viewer/gyroscope-plugin": "file:resources/js/Photo-Sphere-Viewer-main/packages/markers-plugin/dist",
```
Then I could import the modules just like before:
```
import { Viewer } from '@photo-sphere-viewer/core';
import "@photo-sphere-viewer/core/index.css"
import { GyroscopePlugin } from '@photo-sphere-viewer/gyroscope-plugin';
```
