### ISSUE TITLE
Markers Plugin events being fired incorrectly. The enter-marker and leave-marker event get fired simultaneously

### ISSUE THREAD

**Issue by AliHasan71** [mistic100/Photo-Sphere-Viewer#959] opened 2023-05-12 04:34 UTC
### Describe the bug

I have implemented the Markers Plugin to render a wide range of markers in my Cubemap panorama. I have added the `enter-marker` and `leave-marker` events to the markers plugin. However, I am noticing that whenever any marker is hovered over and the cursor is left there, both the enter and leave events are fired back to back.

The best way to reproduce it is by accessing the example code sandbox provided in the official documentation on the website. Here is the link: https://photo-sphere-viewer.js.org/plugins/markers.html#example

Just copy the following code at the bottom of the file.

```
markersPlugin.addEventListener(
  "enter-marker",
  ({ marker, doubleClick, rightClick }) => {
    if (marker.id === "polygon") {
      markersPlugin.updateMarker({
        id: "polygon",
        svgStyle: {
          fill: "blue"
        }
      });
    }
  }
);

markersPlugin.addEventListener(
  "leave-marker",
  ({ marker, doubleClick, rightClick }) => {
    if (marker.id === "polygon") {
      markersPlugin.updateMarker({
        id: "polygon",
        svgStyle: {
          fill: "yellow"
        }
      });
    }
  }
);
```

The above code should basically turn the polygon shown into one with a fill color of blue as long as the mouse is hovered over the marker. Then when it leaves the marker it should turn yellow. But the behavior seen is that it turns yellow right when the mouse is hovered over, as it is also triggering the `leave-marker` event when hovering over the marker.

Any guidance would be greatly appreciated.

### Photo Sphere Viewer version

5.1.5

### Plugins loaded

CompassPlugin, MarkersPlugin

### OS & browser

MacOS and Google Chrome

**Comment by mistic100** [comment] 2023-05-12 08:41
The problem is a bit more complex. The two events are **not** triggered simultaneously, you can test this by just using a console.log is the handlers.

The real problem is that calling "updateMaker" within the "enter-marker" event makes the plugin "loose" the current marker (that's also why the cursor rapidly switch between move and pointer).

---

BTW those events do not have either "doubleClick" or "rightClick" parameters

**Comment by AliHasan71** [comment] 2023-05-12 08:52
@mistic100 Thanks for such a quick response.

That makes sense to me. So what is the recommended approach for updating  the marker for which the event occurs. Like highlighting the shape on hover. This is a common feature that is widely implemented.

**Comment by mistic100** [comment] 2023-05-12 08:53
none, the bug will be fixed, but probably not this month

**Comment by mistic100** [comment] 2023-06-03 07:37
This problem is not present on Firefox. Thanks Chrome !

**Closed** 2023-06-03 07:56 UTC
Labels: bug

**Comment by AliHasan71** [comment] 2023-06-06 23:29
@mistic100 Thanks for the quick fix. I'll give it a try now.

**Comment by AliHasan71** [comment] 2023-07-02 23:13
@mistic100 So I tried with the latest version (5.17) and it seems to have resolved that specific issue I was having but for specific marker types. I have noticed a weird issue with the **ellipse** shape types. When updating only the `svgStyle` of a ellipse marker on hover, the position somehow shifts automatically slightly. This was not happening when using version 5.15.
