### ISSUE TITLE
Visible range prevents autorotate

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#802] opened 2022-12-19 22:54 UTC
### Describe the bug

I have autorotate plugin with this configuration:

```
   [PhotoSphereViewer.AutorotatePlugin, {
     autostartDelay: 3000,
     autorotateSpeed: 0.12,
     autorotateZoomLvl: 2,
     autostartOnIdle: false,
   }],

```
when I zoom in **manually** and then hit the autorotate button the pano zoom out to the "autorotateZoomLvl" and then perform the rotation.

But when I click on a marker from the marker list  that has the "zoomLvl" set, then I hit the autorotate button the pano zoom out to the "autorotateZoomLvl" but the autorotation is not performed.

Check the online demo

### Online demo URL

https://www.tadini.it/panorama/verezzi/panorama_verezzi.htm

### Photo Sphere Viewer version

5.0

### Plugins loaded

autorotate, compass, markers, visible-range

### three.js version

https://cdn.jsdelivr.net/npm/three/build/three.min.js

### OS & browser

win11 - chrome 108

**Comment by mistic100** [comment] 2022-12-20 17:38
Once again this is caused by the visible range plugin, and once again it will be an headache.  
(it has nothing to do with teh markers plugin, you can manually zoom near the blue marker and the behaviour will be the same)

**Comment by mistic100** [comment] 2023-01-10 12:21
Fixed by forcing to change the zoom level before starting the rotation

**Closed** 2023-01-10 12:21 UTC
Labels: bug
