### ISSUE TITLE
Issues with loading WebGL

### ISSUE THREAD

**Issue by alexsaleh** [mistic100/Photo-Sphere-Viewer#1063] opened 2023-09-02 19:08 UTC
### Describe your problem

The viewer loads fine on most browsers and OS but on some specific Windows 10 machines, I get WebGL errors in the console and the panorama image is unable to be loaded. 

Basically it's just a black or white screen. 

It happens on the latest versions of Chrome (116) or Edge.

WebGL is enabled on the browser. Any idea as to how to work around the issue? 

<img width="680" alt="Screenshot 2023-09-02 at 3 00 58 PM" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/16172748/5b645dfd-307a-46c0-b461-ae6c947aaf42">

Thanks!

### Photo Sphere Viewer version

5.1.7

### Plugins loaded

compass

**Comment by mistic100** [comment] 2023-09-02 19:28
Do you see the same error here after 5 seconds https://codesandbox.io/s/distracted-dream-w66hm4 ?

This is the official ThreeJS equirectangular demo with a 5s timeout which emulates what's appens in PSV when a transition is done (disposing the old texture).

Anyway I am really not qualified to debug ThreeJS internals, especially if the problem is on one specific device.

**Comment by alexsaleh** [comment] 2023-09-02 19:34
Yes I do get the same error.

And the weird thing is that sometimes the first panorama is going to load OK, but then on transition is when this will happen with the black screen.

**Comment by mistic100** [comment] 2023-09-02 19:48
Well there is nothing I will be able to do then.

You should open an issue on ThreeJS repository with the above example and your full system specs.

**Comment by mistic100** [comment] 2023-09-02 19:56
Just a though : check that your GPU or integrated graphics drivers are up to date, as well as Windows itself.

**Comment by alexsaleh** [comment] 2023-09-02 20:09
I just get this as well on windows 11, slightly different message "webGL context lost"

<img width="500" alt="Screenshot 2023-09-02 at 4 08 26 PM" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/16172748/2e751395-30f4-49d5-8f12-f2529014c49f">

**Comment by mistic100** [comment] 2023-09-02 21:38
Do you load multiple viewers ? Because this error usually happens when you try to create more WebGL contexts than the browser supports.

**Comment by alexsaleh** [comment] 2023-09-02 23:22
I don't load multiple viewers, but I do change the panorama image quite often. 

I can now reproduce it on different systems with different specs (Mac OS, Win10, Win11). Albeit it happens more often on windows. 

I narrowed the issue down to the following:
- it happens more often if I try to render a new image while the previous one is still rendering (while isPanoReady is false)
- it happens more often with larger panos (we're talking 3-4 MB here)

Here's the same kind of error happening on Mac OS, Chrome 116, after 47 successful panorama image changes. 

![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/16172748/875423ec-7392-4fbd-b19d-0975bd806c02)

**Comment by mistic100** [comment] 2023-09-03 07:54
That's really a critical piece of information you could have say from the start....

Please create an online demo where I can test your setup.

**Comment by mistic100** [comment] 2023-09-04 11:12
I made an update to the renderer to be sure to dispose (remove from the GPU) old unused textures, that was not the case before.

Perhaps your context loss was due to a VRAM overflow.

That does probably does not solve your first isolated issue though, the one you replicate on my Code Sand Box demo.

**Comment by alexsaleh** [comment] 2023-09-04 13:56
I'm trying to find a way to replicate the issue on a code sandbox while loading our images. Will report back

Thank you for the change. I will test it out ASAP, maybe it will help!

**Comment by alexsaleh** [comment] 2023-09-06 15:44
FYI, I managed to work around the issue by splitting the panoramas into tiles and using the tiling adapter. I was not able to reproduce the issue since the tiling, for now. 

 It seems like WebGL doesn't like it if you don't dispose of the old textures especially if they're big. I can re-test with the original panoramas once you release the old texture disposing fix.

**Comment by mistic100** [comment] 2023-09-11 21:00
old textures cleaning released in version 5.4.0

**Closed by mistic100** 2023-09-11 21:00 UTC
Labels: question
